services:
  mysql-db:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: employeeservice_db
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
